apiVersion: v1
kind: Secret
metadata:
    name: dna-frontend-secrets
type: Opaque
# All values must be base64-encoded: echo -n 'value' | base64
# Source of truth: .env.development
data:
    # -- Feature flags --
    NEXT_PUBLIC_DARK_MODE: xxx
    NEXT_PUBLIC_IS_MAINT_MODE: xxx
    NEXT_PUBLIC_IS_PREVIEW_MODE: xxx
    NEXT_PUBLIC_IS_DEBUG_MODE: xxx
    NEXT_PUBLIC_SIMPLE_SIGNUP: xxx
    # -- Analytics --
    NEXT_PUBLIC_GA_DEBUG_MODE: xxx
    NEXT_PUBLIC_GA_TRACKING_CODE: xxx
    NEXT_PUBLIC_FB_APP_ID: xxx
    NEXT_PUBLIC_FB_PIXEL_ID: xxx
    NEXT_PUBLIC_TRACKING: xxx
    NEXT_PUBLIC_TRACKING_GA_ON: xxx
    NEXT_PUBLIC_TRACKING_KM_ON: xxx
    NEXT_PUBLIC_TRACKING_PROVIDER_GA: xxx
    NEXT_PUBLIC_TRACKING_PROVIDER_KM: xxx
    NEXT_PUBLIC_TRACKING_VERBOSE: xxx
    # -- Company info --
    NEXT_PUBLIC_COMING_SOON_COPY: xxx
    NEXT_PUBLIC_COMPANY_EMAIL: xxx
    NEXT_PUBLIC_COMPANY_LEGAL_URL: xxx
    NEXT_PUBLIC_COMPANY_PHONE: xxx
    NEXT_PUBLIC_ENTITY_NAME: xxx
    # -- Site metadata --
    NEXT_PUBLIC_LOGO_PATH: xxx
    NEXT_PUBLIC_PAGE_DESC: xxx
    NEXT_PUBLIC_PAGE_TITLE: xxx
    NEXT_PUBLIC_SHORT_TITLE: xxx
    NEXT_PUBLIC_SITE_DESC: xxx
    NEXT_PUBLIC_SITE_SUBTITLE: xxx
    NEXT_PUBLIC_SITE_TITLE: xxx
    NEXT_PUBLIC_SITE_URL: xxx
    NEXT_PUBLIC_OG_IMG_HEIGHT: xxx
    NEXT_PUBLIC_OG_IMG_PATH: xxx
    NEXT_PUBLIC_OG_IMG_WIDTH: xxx
    NEXT_PUBLIC_PRIVACY_SLUG: xxx
    NEXT_PUBLIC_TERMS_SLUG: xxx
    # -- Social URLs --
    NEXT_PUBLIC_FACEBOOK_URL: xxx
    NEXT_PUBLIC_INSTAGRAM_URL: xxx
    NEXT_PUBLIC_TWITTER_URL: xxx
    NEXT_PUBLIC_VIDEO_URL: xxx
    # -- GoHighLevel --
    NEXT_PUBLIC_GOHIGHLEVEL_FORM_ID: xxx
    NEXT_PUBLIC_GOHIGHLEVEL_LOCATION_ID: xxx
    # -- Google Maps --
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: xxx
    # -- Kontent CMS --
    NEXT_PUBLIC_KONTENT_PROJECT_ID: xxx
    NEXT_PUBLIC_KONTENT_MGMT_KEY: xxx
    # -- Mailchimp --
    NEXT_PUBLIC_MAILCHIMP_API_KEY: xxx
    NEXT_PUBLIC_MAILCHIMP_AUDIENCE_ID: xxx
    NEXT_PUBLIC_MAILCHIMP_CLIENT_KEY: xxx
    NEXT_PUBLIC_MAILCHIMP_ID: xxx
    NEXT_PUBLIC_MAILCHIMP_U: xxx
    NEXT_PUBLIC_MAILCHIMP_URL: xxx
    NEXT_PUBLIC_MAILCHIMP_USERNAME: xxx
    NEXT_PUBLIC_MAILER: xxx
    # -- Mux video --
    NEXT_PUBLIC_MUX_ACCESS_TOKEN_ID: xxx
    NEXT_PUBLIC_MUX_SECRET_KEY: xxx
    # -- SoundCloud --
    NEXT_PUBLIC_SC_CLIENT_ID: xxx
    NEXT_PUBLIC_SC_CLIENT_SECRET: xxx
    # -- Spree API --
    NEXT_PUBLIC_SPREE_ACCESS_TOKEN: xxx
    NEXT_PUBLIC_SPREE_ACCESS_TOKEN_BKP: xxx
    NEXT_PUBLIC_SPREE_API_URL: xxx
